### ISSUE TITLE
Release new 1.6.24 version 

### ISSUE THREAD

**Issue by enkidulan** [plone/plonetheme.barceloneta#145]

**Comment by pnicolli** [comment]
I noticed version 1.6.24 is now released on pypi. I also noticed it is marked as the latest release. While 1.6.24 is probably the latest uploaded release, I believe that 1.8 should still be marked as the latest on pypi.

Screenshot of the [pypi page](https://pypi.python.org/pypi/plonetheme.barceloneta/1.8):
![barcelonetaversion](https://user-images.githubusercontent.com/14176608/36585067-a29415a8-187c-11e8-9b5c-2de864060010.jpg)

**Comment by gforcada** [comment]
@pnicolli I guess this is due to the automatic way pypi handles new releases, thinking that they always the latest.

In a project like plone where we have, right now, 3 parallel release series (4.3.x, 5.0.x and 5.1) whenever we (the release team) upload new versions, pypi gets confused.

I see that on the newer pypi (still beta) it is fixed already:
https://pypi.org/project/plonetheme.barceloneta/
https://pypi.org/project/plonetheme.barceloneta/#history

**Comment by gforcada** [comment]
@enkidulan the release was made, closing. Reopen if needed.
