### ISSUE TITLE
@@test_rendering not found

### ISSUE THREAD

**Issue by fulv** [plone/plonetheme.barceloneta#59]
@sneridagh in your ploneconf talk you said we can use `@@test_rendering`, but I don't think it's available.

**Comment by pbauer** [comment]
It is: http://demo.plone.de/test_rendering

**Comment by davilima6** [comment]
It'd be awesome to have some portlets in there because this a very useful page for designers that don't know Plone. However I see those aren't real portlets and I also can't assign portlets to a template:

* https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_templates/test_rendering.pt

What would be the best way to improve from here? First idea would be to modify this template so it displays portlet managers if they are assigned in context, what do you think?

**Comment by fulv** [comment]
it's a **-gasp-** skin template?  :astonished:

**Comment by fulv** [comment]
I guess since it'll have to be turned into a view, anyway, yeah, we can include portlet managers.

**Comment by djay** [comment]
One idea was for it to automatically include custom tinymce styles from CSS
style sheets and perhaps have a way to specify what the example HTML should
be in the CSS. This feature should be part of plone though, not
barceloneta.

**Comment by fulv** [comment]
I moved this to Products.CMFPlone#1234
