### ISSUE TITLE
plone-compile-resources raises error ( since last commits ?)

### ISSUE THREAD

**Issue by fgrcon** [plone/plonetheme.barceloneta#75]
buildout.coredev 5.0 (last c292661)
````
....
Running "less:thememapper" (less) task
>> NameError: .font-face is undefined in https://raw.githubusercontent.com/plone/plonetheme.barceloneta/master/plonetheme/barceloneta/theme/less/fonts.plone.less on line 4, column 1:
>> 3 // 300 Light
>> 4 .font-face(
>> 5     @font-path:     'roboto/';
Warning: Error compiling /usr/local/p5dev/buildout.coredev/eggs/plone.app.theming-1.2.16-py2.7.egg/plone/app/theming/browser/resources/thememapper.less Use --force to continue.
````

**Comment by allcaps** [comment]
I added a font-face mixin because previously the font declarations had repetitive code and some mistakes. Less builds fine on command line with `grunt less`. Building the thememapper TTW the `.font-face` mixin that lives in `mixin.font.plone.less` is missing.

When I add the mixin import statement to [plone.app.theming/.../thememapper.less](
https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/browser/resources/thememapper.less) 'thememapper' build compiles fine TTW.

FYI: `@import url("https://raw.githubusercontent.com/plone/plonetheme.barceloneta/master/plonetheme/barceloneta/theme/less/mixin.font.plone.less");`

It also confuses me that all those imports point to github.com (outside resource) and the master branch (can change all the time). [barceloneta.plone.local.less](https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/barceloneta.plone.local.less) also points to github.com and a master branch.

@vangheem and @bloodbare: Shouldn't all those imports be available within the current site domain? This seems wrong and can cause trouble in many ways.

**Comment by vangheem** [comment]
Probably need to find a better solution but it's difficult. Grunt builds do not run on an active instance--they run on static files in directories. plone-compile-resources is different than the theme editor's compile less. The theme editor using JS to build it and doesn't do the image resource inlining.

**Comment by allcaps** [comment]
@vangheem: I can use some guidance here. I think these are my options:

- A: Import mixin.font.plone.less in thememapper.less. When thememapper is build the font mixin will be loaded and all will work fine.
- B: Delete the mixin.font.plone.less file and add the mixin itself to the top of fonts.plone.less. The mixin can't be used separately.
- C: Drop the mixin and write the @font-face declarations out. Just like before. No mixin at all.
- D: Something else ...

This bug happens in the latest Barceloneta release that is part of Plone 5.0.2 soft release.

**Comment by vangheem** [comment]
I think option A is the best choice. Thanks.

**Comment by allcaps** [comment]
https://github.com/plone/plone.app.theming/commit/6e6603861249eefc8c73ab36d7ec9770bc964f38
